#!/usr/bin/env bash
set -euo pipefail

# Production Database Configuration Fix
# Fixes the DATABASE_PATH misconfiguration that caused the Nov 12 deployment failure

PROD_DIR="/opt/app-monitor"
DATA_DIR="${PROD_DIR}/shared/backend/data"
ENV_FILE="${PROD_DIR}/shared/.env"
DB_NAME="app-monitor.db"

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

fatal() {
  log "ERROR: $*"
  exit 1
}

# Check if running with appropriate permissions
if [[ ! -w "$PROD_DIR" ]]; then
  fatal "No write access to $PROD_DIR. Run with: sudo -u jdubz $0"
fi

log "Starting production database configuration fix..."

# Step 1: Create data directory structure
log "Creating data directory: $DATA_DIR"
mkdir -p "$DATA_DIR"

# Step 2: Move existing database files if they exist in wrong location
for db_file in app-monitor.db; do
  old_path="${PROD_DIR}/${db_file}"
  new_path="${DATA_DIR}/${db_file}"
  
  if [[ -f "$old_path" && ! -f "$new_path" ]]; then
    log "Moving ${db_file} to data directory..."
    mv "$old_path" "$new_path"
  elif [[ -f "$old_path" && -f "$new_path" ]]; then
    log "WARNING: ${db_file} exists in both locations, keeping newer one"
    if [[ "$old_path" -nt "$new_path" ]]; then
      log "Old location is newer, moving it..."
      mv "$old_path" "$new_path"
    else
      log "New location is newer, removing old one..."
      rm "$old_path"
    fi
  fi
done

# Step 3: Fix permissions
log "Setting correct permissions..."
chown -R jdubz:jdubz "$DATA_DIR"
chmod 755 "$DATA_DIR"
chmod 644 "$DATA_DIR"/*.db 2>/dev/null || true

# Step 4: Update .env file
log "Configuring DATABASE_PATH in .env..."

if [[ ! -f "$ENV_FILE" ]]; then
  log "Creating .env file..."
  cat > "$ENV_FILE" << EOF
# Generated by fix-production-database.sh on $(date)
NODE_ENV=production
DATABASE_PATH=${DATA_DIR}/${DB_NAME}
PORT=5001
EOF
  chown jdubz:jdubz "$ENV_FILE"
  chmod 600 "$ENV_FILE"
else
  # Check if DATABASE_PATH already exists
  if grep -q "^DATABASE_PATH=" "$ENV_FILE"; then
    log "Updating existing DATABASE_PATH..."
    sed -i "s|^DATABASE_PATH=.*|DATABASE_PATH=${DATA_DIR}/${DB_NAME}|" "$ENV_FILE"
  else
    log "Adding DATABASE_PATH to .env..."
    echo "DATABASE_PATH=${DATA_DIR}/${DB_NAME}" >> "$ENV_FILE"
  fi
fi

# Step 5: Verify configuration
log "Verifying configuration..."

if [[ ! -d "$DATA_DIR" ]]; then
  fatal "Data directory was not created: $DATA_DIR"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  fatal "Environment file was not created: $ENV_FILE"
fi

if ! grep -q "^DATABASE_PATH=" "$ENV_FILE"; then
  fatal "DATABASE_PATH not found in .env file"
fi

configured_path=$(grep "^DATABASE_PATH=" "$ENV_FILE" | cut -d'=' -f2)
log "Configured DATABASE_PATH: $configured_path"

# Step 6: Test database connectivity (if database exists)
db_path="${DATA_DIR}/${DB_NAME}"
if [[ -f "$db_path" ]]; then
  log "Testing database connectivity..."
  if node -e "const db = require('better-sqlite3')('$db_path'); db.close();" 2>&1; then
    log "✅ Database is accessible"
  else
    log "⚠️  Warning: Database exists but cannot be opened"
  fi
  
  # Check migrations
  log "Checking applied migrations..."
  node -e "
    const Database = require('better-sqlite3');
    const db = new Database('$db_path', { readonly: true });
    try {
      const migrations = db.prepare('SELECT * FROM migrations ORDER BY id').all();
      console.log('Applied migrations:', migrations.length);
      migrations.forEach(m => console.log('  -', m.id, m.name));
    } catch (e) {
      console.log('Migrations table does not exist (fresh database)');
    }
    db.close();
  " 2>&1 || log "Could not read migrations (database may be new)"
else
  log "ℹ️  Database file does not exist yet (will be created on first startup)"
fi

# Step 7: Summary
log ""
log "✅ Production database configuration fixed!"
log ""
log "Summary:"
log "  Data directory: $DATA_DIR"
log "  Database path: $db_path"
log "  Environment file: $ENV_FILE"
log ""
log "Next steps:"
log "  1. Restart backend service: sudo systemctl restart app-monitor-backend@5001.service"
log "  2. Check status: sudo systemctl status app-monitor-backend@5001.service"
log "  3. View logs: sudo journalctl -u app-monitor-backend@5001.service -n 50"
log "  4. Test health: curl http://localhost:5001/health"
log ""
